# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [published]
  
  workflow_dispatch:
    inputs: 
      prerelease:
        type: boolean
        description: Is it a pre-release publish?
        default: true

env:
  prerelease: ${{ github.event.release.prerelease }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn lerna run publish  ${{ github.event.inputs.prerelease && '--conventional-prerelease' || '--conventional-commits' }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
