# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: Pre-release
        default: true
        required: false

env:
  prerelease: ${{ github.event.release.prerelease }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn lerna version --yes --conventional-commits --create-release github ${{ github.event.inputs.prerelease && '--conventional-prerelease' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
